FROM bw-python-base:latest

WORKDIR /app

COPY python/pyproject.toml /app/pyproject.toml
COPY python/src/ /app/src/
COPY proto/ /app/proto/

RUN mkdir -p /app/generated && \
    protoc \
    -I /app/proto \
      --python_out=/app/generated \
      $(find /app/proto -name "*.proto")

RUN pip install --no-cache-dir .
ENV PYTHONPATH=/app/src:/app/generated
